[package]
name = "guessing"
version = "0.1.0"
authors = ["nachiket kanore <nachiket.kanore@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
anyhow = "1.0.52"
